name: Work Flows
on: push
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4 
            - name: test job welcome message
              run: |
                   echo "executing the test job..." 
                   cat README.md  
             
